import { BriefcaseBusiness, ExternalLink, KanbanSquare, List, Plus, Search, Trash2, X, WandSparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '../components/ui/Button.jsx';
import { api } from '../lib/api.js';

const statuses = ['Applied', 'Assessment', 'Interview', 'Offer', 'Rejected', 'Withdrawn'];
const statusClass = { Applied: 'status-applied', Assessment: 'status-assessment', Interview: 'status-interview', Offer: 'status-offer', Rejected: 'status-rejected', Withdrawn: 'status-withdrawn' };

function JobForm({ onClose, onSaved }) {
  const [form, setForm] = useState({ company: '', role: '', jobUrl: '', description: '', status: 'Applied', applicationDate: new Date().toISOString().slice(0, 10), notes: '' });
  const [error, setError] = useState('');
  const [analysis, setAnalysis] = useState(null);
  const analyze = useMutation({
    mutationFn: () => api.post('/jobs/analyze', { company: form.company, role: form.role, description: form.description }),
    onSuccess: (response) => { setAnalysis(response.data.data.analysis); setError(''); },
    onError: (requestError) => setError(requestError.message || 'Unable to analyze this job description.'),
  });
  const save = useMutation({
    mutationFn: () => api.post('/jobs', { ...form, applicationDate: form.applicationDate ? new Date(`${form.applicationDate}T00:00:00.000Z`).toISOString() : null }),
    onSuccess: () => onSaved(),
    onError: (requestError) => setError(requestError.message || 'Unable to save this application.'),
  });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="add-job-title"><header className="modal-header"><div><p className="eyebrow">Application tracker</p><h2 id="add-job-title">Add a job</h2></div><button className="icon-btn" aria-label="Close" onClick={onClose}><X size={18} /></button></header><div className="form-grid job-form"><label className="field"><span>Company</span><input autoFocus value={form.company} onChange={(event) => update('company', event.target.value)} placeholder="e.g. Acme Inc." /></label><label className="field"><span>Role</span><input value={form.role} onChange={(event) => update('role', event.target.value)} placeholder="e.g. Frontend Engineer" /></label><label className="field"><span>Status</span><select value={form.status} onChange={(event) => update('status', event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="field"><span>Application date</span><input type="date" value={form.applicationDate} onChange={(event) => update('applicationDate', event.target.value)} /></label><label className="field field-wide"><span>Job URL <small>Optional</small></span><input type="url" value={form.jobUrl} onChange={(event) => update('jobUrl', event.target.value)} placeholder="https://..." /></label><label className="field field-wide"><span>Job description <small>Paste for AI analysis</small></span><textarea rows="5" value={form.description} onChange={(event) => { update('description', event.target.value); setAnalysis(null); }} placeholder="Paste the responsibilities and requirements..." /></label><label className="field field-wide"><span>Notes <small>Optional</small></span><textarea rows="3" value={form.notes} onChange={(event) => update('notes', event.target.value)} placeholder="What do you want to remember?" /></label></div>{analysis && <div className="job-analysis"><strong>{analysis.summary}</strong><span>Skills: {analysis.extractedSkills?.join(', ') || 'None identified'}</span><span>Keywords: {analysis.keywords?.join(', ') || 'None identified'}</span>{analysis.resumeMatch !== null && analysis.resumeMatch !== undefined && <span>Resume match: {analysis.resumeMatch}/100</span>}</div>}{error && <p className="form-error">{error}</p>}<footer className="modal-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="secondary" onClick={() => analyze.mutate()} disabled={analyze.isPending || form.description.trim().length < 30}><WandSparkles size={15} /> {analyze.isPending ? 'Analyzing...' : 'Analyze with AI'}</Button><Button onClick={() => save.mutate()} disabled={save.isPending || !form.company.trim() || !form.role.trim()}>{save.isPending ? 'Saving...' : 'Save application'}</Button></footer></section></div>;
}

function JobRow({ job, onDelete, onStatusChange }) {
  return <article className="job-row"><div className="job-logo">{job.company.slice(0, 1).toUpperCase()}</div><div className="job-main"><strong>{job.role}</strong><span>{job.company} {job.jobUrl && <a href={job.jobUrl} target="_blank" rel="noreferrer" aria-label={`Open ${job.role} job listing`}><ExternalLink size={12} /></a>}</span></div><select className={`status-select ${statusClass[job.status]}`} value={job.status} onChange={(event) => onStatusChange(job._id, event.target.value)} aria-label={`Status for ${job.role}`}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><span className="job-date">{job.applicationDate ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(job.applicationDate)) : '—'}</span><button className="icon-btn" aria-label={`Delete ${job.role} at ${job.company}`} onClick={() => onDelete(job._id)}><Trash2 size={15} /></button></article>;
}

export function JobsPage() {
  const [view, setView] = useState('list');
  const [showForm, setShowForm] = useState(false);
  const [search, setSearch] = useState('');
  const queryClient = useQueryClient();
  const { data: jobs = [], isLoading, isError } = useQuery({ queryKey: ['jobs'], queryFn: async () => (await api.get('/jobs')).data.data.jobs });
  const remove = useMutation({ mutationFn: (id) => api.delete(`/jobs/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['jobs'] }) });
  const update = useMutation({ mutationFn: ({ id, status }) => api.put(`/jobs/${id}`, { status }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['jobs'] }) });
  const filtered = useMemo(() => jobs.filter((job) => `${job.company} ${job.role}`.toLowerCase().includes(search.toLowerCase())), [jobs, search]);
  const counts = statuses.reduce((result, status) => ({ ...result, [status]: jobs.filter((job) => job.status === status).length }), {});
  return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">Application tracker</p><h1>Keep every opportunity moving.</h1><p className="subheading">Track applications, interviews, and offers in one focused workspace.</p></div><Button onClick={() => setShowForm(true)}><Plus size={16} /> Add a job</Button></section><section className="job-stats">{[['Total', jobs.length, ''], ...statuses.slice(0, 4).map((status) => [status, counts[status], statusClass[status]])].map(([label, count, className]) => <div className="job-stat" key={label}><span className={className}>{label}</span><strong>{count}</strong></div>)}</section><section className="card jobs-card"><header className="jobs-toolbar"><div className="search-field"><Search size={16} /><input aria-label="Search jobs" placeholder="Search company or role" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="view-toggle"><button className={view === 'list' ? 'active' : ''} aria-label="List view" onClick={() => setView('list')}><List size={16} /></button><button className={view === 'kanban' ? 'active' : ''} aria-label="Kanban view" onClick={() => setView('kanban')}><KanbanSquare size={16} /></button></div></header>{isLoading && <div className="resume-loading">Loading applications…</div>}{isError && <p className="form-note">We couldn&apos;t load your applications. Please retry.</p>}{!isLoading && !isError && !filtered.length && <div className="resume-empty"><BriefcaseBusiness size={24} /><p>{jobs.length ? 'No matching applications' : 'Your application pipeline is empty'}</p><span>{jobs.length ? 'Try a different search.' : 'Add your first job to start tracking momentum.'}</span></div>}{view === 'list' && !!filtered.length && <div className="job-list">{filtered.map((job) => <JobRow key={job._id} job={job} onDelete={(id) => remove.mutate(id)} onStatusChange={(id, status) => update.mutate({ id, status })} />)}</div>}{view === 'kanban' && <div className="kanban-grid">{statuses.slice(0, 4).map((status) => <div className="kanban-column" key={status}><header><span className={statusClass[status]}>{status}</span><b>{filtered.filter((job) => job.status === status).length}</b></header>{filtered.filter((job) => job.status === status).map((job) => <div className="kanban-card" key={job._id}><strong>{job.role}</strong><span>{job.company}</span><select className={`status-select ${statusClass[job.status]}`} value={job.status} onChange={(event) => update.mutate({ id: job._id, status: event.target.value })} aria-label={`Status for ${job.role}`}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div>)}</div>)}</div>}</section>{showForm && <JobForm onClose={() => setShowForm(false)} onSaved={() => { setShowForm(false); queryClient.invalidateQueries({ queryKey: ['jobs'] }); }} />}</div>;
}
